import React, { createContext, useContext, useState, useEffect, useCallback } from "react";

type Language = "en" | "sw" | "fr" | "pt";

const LANG_LABELS: Record<Language, string> = {
  en: "English",
  sw: "Kiswahili",
  fr: "Français",
  pt: "Português",
};

// Translation keys
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.explore": "Explore",
    "nav.community": "Community",
    "nav.products": "Products",
    "nav.academy": "Academy",
    "nav.postHustle": "Post Hustle",
    "nav.saved": "Saved",
    "nav.bookings": "Bookings",
    "nav.messages": "Messages",
    "nav.admin": "Admin Panel",
    "nav.dashboard": "Dashboard",
    "nav.profile": "Profile",
    "nav.settings": "Settings",
    "nav.signOut": "Sign Out",
    "nav.signIn": "Sign In",
    "nav.wallet": "Wallet",
    // Hero
    "hero.badge": "Community-Powered Marketplace",
    "hero.title": "Discover Local",
    "hero.titleHighlight": "Hustles",
    "hero.titleEnd": "Near You",
    "hero.subtitle": "Connect with talented small businesses and freelancers in your community.",
    "hero.search": "Search hustles...",
    "hero.explore": "Explore",
    // Sections
    "section.featured": "🔥 Featured Hustles",
    "section.featuredSub": "Premium hustlers showcasing their best",
    "section.viewAll": "View All",
    "section.categories": "Browse by Category",
    "section.latest": "Latest Hustles",
    "section.noHustles": "No hustles yet. Be the first to post!",
    "section.postYour": "Post Your Hustle",
    // Boost
    "boost.title": "🚀 Boost Your Hustle",
    "boost.subtitle": "Get more views and appear at the top. Starting from R19.",
    "boost.cta": "Boost Now",
    // CTA cards
    "cta.academy": "Hustler Academy 🎓",
    "cta.academySub": "Free lessons on business, marketing & money",
    "cta.academyBtn": "Start Learning",
    "cta.community": "Community Chat 💬",
    "cta.communitySub": "Ask questions, share services & connect",
    "cta.communityBtn": "Join Chat",
    "cta.products": "Sell Products 🛍️",
    "cta.productsSub": "Sell materials, bundle with your services",
    "cta.productsBtn": "Start Selling",
    "cta.bookings": "Smart Bookings 📅",
    "cta.bookingsSub": "Manage your schedule like a pro",
    "cta.bookingsBtn": "View Calendar",
    // Auth
    "cta.readyTitle": "Ready to Share Your Hustle?",
    "cta.readySub": "Join the community and start connecting with customers today.",
    "cta.getStarted": "Get Started Free",
    // Footer
    "footer.tagline": "Community-driven marketplace.",
    // Common
    "common.all": "All",
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.submit": "Submit",
    "common.report": "Report",
    "common.back": "Back",
    // Wallet
    "wallet.title": "Wallet",
    "wallet.balance": "Balance",
    "wallet.send": "Send",
    "wallet.withdraw": "Withdraw",
    "wallet.deposit": "Deposit",
    "wallet.transactions": "Transactions",
    "wallet.noTransactions": "No transactions yet",
    // Products
    "products.title": "Products",
    "products.subtitle": "Buy materials or bundle with services",
    "products.sell": "Sell Product",
    "products.noProducts": "No products listed yet",
    "products.beFirst": "Be the first to sell something!",
    // Report
    "report.title": "Report Scam",
    "report.reason": "Reason",
    "report.description": "Description",
    "report.submit": "Submit Report",
    "report.success": "Report submitted. We'll review it shortly.",
    // Settings
    "settings.language": "Language",
    "settings.languageDesc": "Choose your preferred language",
    "settings.dataMode": "Ultra-Low Data Mode",
    "settings.dataModeDesc": "Reduce data usage for slow connections",
    "settings.textOnly": "Text-Only Mode",
    "settings.textOnlyDesc": "Hide images and media to save data",
    "settings.compressImages": "Compress Images",
    "settings.compressImagesDesc": "Load lower quality images",
  },
  sw: {
    "nav.explore": "Gundua",
    "nav.community": "Jamii",
    "nav.products": "Bidhaa",
    "nav.academy": "Chuo",
    "nav.postHustle": "Weka Kazi",
    "nav.saved": "Zilizohifadhiwa",
    "nav.bookings": "Nafasi",
    "nav.messages": "Ujumbe",
    "nav.admin": "Paneli ya Msimamizi",
    "nav.dashboard": "Dashibodi",
    "nav.profile": "Wasifu",
    "nav.settings": "Mipangilio",
    "nav.signOut": "Ondoka",
    "nav.signIn": "Ingia",
    "nav.wallet": "Pochi",
    "hero.badge": "Soko la Jamii",
    "hero.title": "Gundua",
    "hero.titleHighlight": "Biashara",
    "hero.titleEnd": "Karibu Nawe",
    "hero.subtitle": "Ungana na wafanyabiashara wadogo wenye talanta katika jamii yako.",
    "hero.search": "Tafuta biashara...",
    "hero.explore": "Gundua",
    "section.featured": "🔥 Biashara Bora",
    "section.featuredSub": "Wafanyabiashara bora wanaonyesha huduma zao",
    "section.viewAll": "Tazama Zote",
    "section.categories": "Tafuta kwa Aina",
    "section.latest": "Biashara Mpya",
    "section.noHustles": "Hakuna biashara bado. Kuwa wa kwanza!",
    "section.postYour": "Weka Biashara Yako",
    "boost.title": "🚀 Boresha Biashara Yako",
    "boost.subtitle": "Pata maoni zaidi na uonekane juu. Kuanzia R19.",
    "boost.cta": "Boresha Sasa",
    "cta.academy": "Chuo cha Biashara 🎓",
    "cta.academySub": "Masomo ya bure ya biashara na masoko",
    "cta.academyBtn": "Anza Kujifunza",
    "cta.community": "Mazungumzo ya Jamii 💬",
    "cta.communitySub": "Uliza maswali, shiriki huduma na uungane",
    "cta.communityBtn": "Jiunge na Mazungumzo",
    "cta.products": "Uza Bidhaa 🛍️",
    "cta.productsSub": "Uza vifaa, unganisha na huduma zako",
    "cta.productsBtn": "Anza Kuuza",
    "cta.bookings": "Nafasi za Kisasa 📅",
    "cta.bookingsSub": "Simamia ratiba yako kama mtaalamu",
    "cta.bookingsBtn": "Tazama Kalenda",
    "cta.readyTitle": "Tayari Kushiriki Biashara Yako?",
    "cta.readySub": "Jiunge na jamii na uanze kuungana na wateja leo.",
    "cta.getStarted": "Anza Bure",
    "footer.tagline": "Soko linaloendeshwa na jamii.",
    "common.all": "Zote",
    "common.loading": "Inapakia...",
    "common.save": "Hifadhi",
    "common.cancel": "Ghairi",
    "common.delete": "Futa",
    "common.edit": "Hariri",
    "common.submit": "Wasilisha",
    "common.report": "Ripoti",
    "common.back": "Rudi",
    "wallet.title": "Pochi",
    "wallet.balance": "Salio",
    "wallet.send": "Tuma",
    "wallet.withdraw": "Toa",
    "wallet.deposit": "Weka",
    "wallet.transactions": "Miamala",
    "wallet.noTransactions": "Hakuna miamala bado",
    "products.title": "Bidhaa",
    "products.subtitle": "Nunua vifaa au uunganishe na huduma",
    "products.sell": "Uza Bidhaa",
    "products.noProducts": "Hakuna bidhaa bado",
    "products.beFirst": "Kuwa wa kwanza kuuza!",
    "report.title": "Ripoti Ulaghai",
    "report.reason": "Sababu",
    "report.description": "Maelezo",
    "report.submit": "Wasilisha Ripoti",
    "report.success": "Ripoti imewasilishwa. Tutaikagua hivi karibuni.",
    "settings.language": "Lugha",
    "settings.languageDesc": "Chagua lugha yako unayopendelea",
    "settings.dataMode": "Hali ya Data Ndogo",
    "settings.dataModeDesc": "Punguza matumizi ya data kwa mitandao polepole",
    "settings.textOnly": "Maandishi Pekee",
    "settings.textOnlyDesc": "Ficha picha na media ili kuhifadhi data",
    "settings.compressImages": "Bana Picha",
    "settings.compressImagesDesc": "Pakia picha za ubora wa chini",
  },
  fr: {
    "nav.explore": "Explorer",
    "nav.community": "Communauté",
    "nav.products": "Produits",
    "nav.academy": "Académie",
    "nav.postHustle": "Publier",
    "nav.saved": "Sauvegardés",
    "nav.bookings": "Réservations",
    "nav.messages": "Messages",
    "nav.admin": "Panneau Admin",
    "nav.dashboard": "Tableau de bord",
    "nav.profile": "Profil",
    "nav.settings": "Paramètres",
    "nav.signOut": "Déconnexion",
    "nav.signIn": "Connexion",
    "nav.wallet": "Portefeuille",
    "hero.badge": "Marché Communautaire",
    "hero.title": "Découvrez les",
    "hero.titleHighlight": "Services",
    "hero.titleEnd": "Près de Vous",
    "hero.subtitle": "Connectez-vous avec des petites entreprises talentueuses de votre communauté.",
    "hero.search": "Rechercher des services...",
    "hero.explore": "Explorer",
    "section.featured": "🔥 Services en Vedette",
    "section.featuredSub": "Les meilleurs prestataires présentent leurs services",
    "section.viewAll": "Voir Tout",
    "section.categories": "Parcourir par Catégorie",
    "section.latest": "Derniers Services",
    "section.noHustles": "Pas encore de services. Soyez le premier!",
    "section.postYour": "Publier Votre Service",
    "boost.title": "🚀 Boostez Votre Service",
    "boost.subtitle": "Plus de visibilité et en haut de page. À partir de R19.",
    "boost.cta": "Booster",
    "cta.academy": "Académie 🎓",
    "cta.academySub": "Cours gratuits sur le business et le marketing",
    "cta.academyBtn": "Commencer",
    "cta.community": "Chat Communautaire 💬",
    "cta.communitySub": "Posez des questions et partagez vos services",
    "cta.communityBtn": "Rejoindre",
    "cta.products": "Vendre des Produits 🛍️",
    "cta.productsSub": "Vendez du matériel, combinez avec vos services",
    "cta.productsBtn": "Commencer à Vendre",
    "cta.bookings": "Réservations Intelligentes 📅",
    "cta.bookingsSub": "Gérez votre planning comme un pro",
    "cta.bookingsBtn": "Voir le Calendrier",
    "cta.readyTitle": "Prêt à Partager Votre Service?",
    "cta.readySub": "Rejoignez la communauté et connectez-vous avec des clients.",
    "cta.getStarted": "Commencer Gratuitement",
    "footer.tagline": "Marché communautaire.",
    "common.all": "Tout",
    "common.loading": "Chargement...",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.submit": "Soumettre",
    "common.report": "Signaler",
    "common.back": "Retour",
    "wallet.title": "Portefeuille",
    "wallet.balance": "Solde",
    "wallet.send": "Envoyer",
    "wallet.withdraw": "Retirer",
    "wallet.deposit": "Déposer",
    "wallet.transactions": "Transactions",
    "wallet.noTransactions": "Aucune transaction",
    "products.title": "Produits",
    "products.subtitle": "Achetez du matériel ou combinez avec des services",
    "products.sell": "Vendre un Produit",
    "products.noProducts": "Aucun produit listé",
    "products.beFirst": "Soyez le premier à vendre!",
    "report.title": "Signaler une Arnaque",
    "report.reason": "Raison",
    "report.description": "Description",
    "report.submit": "Soumettre le Signalement",
    "report.success": "Signalement soumis. Nous l'examinerons sous peu.",
    "settings.language": "Langue",
    "settings.languageDesc": "Choisissez votre langue préférée",
    "settings.dataMode": "Mode Données Réduites",
    "settings.dataModeDesc": "Réduire l'utilisation des données",
    "settings.textOnly": "Mode Texte Seul",
    "settings.textOnlyDesc": "Masquer les images pour économiser les données",
    "settings.compressImages": "Compresser les Images",
    "settings.compressImagesDesc": "Charger des images de qualité inférieure",
  },
  pt: {
    "nav.explore": "Explorar",
    "nav.community": "Comunidade",
    "nav.products": "Produtos",
    "nav.academy": "Academia",
    "nav.postHustle": "Publicar",
    "nav.saved": "Salvos",
    "nav.bookings": "Reservas",
    "nav.messages": "Mensagens",
    "nav.admin": "Painel Admin",
    "nav.dashboard": "Painel",
    "nav.profile": "Perfil",
    "nav.settings": "Configurações",
    "nav.signOut": "Sair",
    "nav.signIn": "Entrar",
    "nav.wallet": "Carteira",
    "hero.badge": "Mercado Comunitário",
    "hero.title": "Descubra",
    "hero.titleHighlight": "Serviços",
    "hero.titleEnd": "Perto de Você",
    "hero.subtitle": "Conecte-se com pequenos negócios talentosos da sua comunidade.",
    "hero.search": "Buscar serviços...",
    "hero.explore": "Explorar",
    "section.featured": "🔥 Serviços em Destaque",
    "section.featuredSub": "Os melhores prestadores mostrando seus serviços",
    "section.viewAll": "Ver Tudo",
    "section.categories": "Navegar por Categoria",
    "section.latest": "Últimos Serviços",
    "section.noHustles": "Nenhum serviço ainda. Seja o primeiro!",
    "section.postYour": "Publique Seu Serviço",
    "boost.title": "🚀 Impulsione Seu Serviço",
    "boost.subtitle": "Mais visibilidade e no topo da página. A partir de R19.",
    "boost.cta": "Impulsionar",
    "cta.academy": "Academia 🎓",
    "cta.academySub": "Aulas gratuitas de negócios e marketing",
    "cta.academyBtn": "Começar",
    "cta.community": "Chat da Comunidade 💬",
    "cta.communitySub": "Faça perguntas e compartilhe serviços",
    "cta.communityBtn": "Participar",
    "cta.products": "Vender Produtos 🛍️",
    "cta.productsSub": "Venda materiais, combine com seus serviços",
    "cta.productsBtn": "Começar a Vender",
    "cta.bookings": "Reservas Inteligentes 📅",
    "cta.bookingsSub": "Gerencie sua agenda como um profissional",
    "cta.bookingsBtn": "Ver Calendário",
    "cta.readyTitle": "Pronto para Compartilhar Seu Serviço?",
    "cta.readySub": "Junte-se à comunidade e conecte-se com clientes hoje.",
    "cta.getStarted": "Começar Grátis",
    "footer.tagline": "Mercado comunitário.",
    "common.all": "Todos",
    "common.loading": "Carregando...",
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.delete": "Excluir",
    "common.edit": "Editar",
    "common.submit": "Enviar",
    "common.report": "Denunciar",
    "common.back": "Voltar",
    "wallet.title": "Carteira",
    "wallet.balance": "Saldo",
    "wallet.send": "Enviar",
    "wallet.withdraw": "Sacar",
    "wallet.deposit": "Depositar",
    "wallet.transactions": "Transações",
    "wallet.noTransactions": "Nenhuma transação ainda",
    "products.title": "Produtos",
    "products.subtitle": "Compre materiais ou combine com serviços",
    "products.sell": "Vender Produto",
    "products.noProducts": "Nenhum produto listado",
    "products.beFirst": "Seja o primeiro a vender!",
    "report.title": "Denunciar Fraude",
    "report.reason": "Motivo",
    "report.description": "Descrição",
    "report.submit": "Enviar Denúncia",
    "report.success": "Denúncia enviada. Analisaremos em breve.",
    "settings.language": "Idioma",
    "settings.languageDesc": "Escolha seu idioma preferido",
    "settings.dataMode": "Modo de Dados Reduzidos",
    "settings.dataModeDesc": "Reduzir uso de dados para conexões lentas",
    "settings.textOnly": "Modo Texto",
    "settings.textOnlyDesc": "Ocultar imagens e mídia para economizar dados",
    "settings.compressImages": "Comprimir Imagens",
    "settings.compressImagesDesc": "Carregar imagens de qualidade inferior",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languages: typeof LANG_LABELS;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

const detectLanguage = (): Language => {
  const saved = localStorage.getItem("app_language");
  if (saved && saved in LANG_LABELS) return saved as Language;
  const browserLang = navigator.language.split("-")[0];
  if (browserLang in LANG_LABELS) return browserLang as Language;
  return "en";
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLang] = useState<Language>(detectLanguage);

  const setLanguage = useCallback((lang: Language) => {
    setLang(lang);
    localStorage.setItem("app_language", lang);
    document.documentElement.lang = lang;
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = useCallback((key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages: LANG_LABELS }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
